export const mockTree = [
  {
    type: "RECTANGLE",
    x: -770,
    y: 16,
    width: 1920,
    height: 1080,
    fills: [{ type: "SOLID", color: { r: 253, g: 242, b: 248 }, opacity: 1 }],
    topLeftRadius: 0,
    topRightRadius: 0,
    bottomRightRadius: 0,
    bottomLeftRadius: 0,
  },
  {
    type: "RECTANGLE",
    x: 61,
    y: 512,
    width: 259,
    height: 88,
    fills: [{ type: "SOLID", color: { r: 0, g: 0, b: 0 }, opacity: 1 }],
    topLeftRadius: 4,
    topRightRadius: 4,
    bottomRightRadius: 4,
    bottomLeftRadius: 4,
  },
  {
    x: 93,
    y: 544,
    width: 195,
    height: 24,
    type: "TEXT",
    characters: "This is a centered particle.",
    fills: [{ type: "SOLID", color: { r: 255, g: 255, b: 255 }, opacity: 1 }],
    lineHeight: { unit: "PIXELS", value: 24 },
    fontSize: 16,
    fontFamily: "Work Sans, sans-serif",
    textAlignHorizontal: "center",
  },
];
