[
  { type: "FRAME", width: 380, height: 756, x: 0, y: 0 },
  {
    type: "RECTANGLE",
    x: 0,
    y: 357,
    width: 235,
    height: 399,
    fills: [],
    topLeftRadius: 0,
    topRightRadius: 0,
    bottomRightRadius: 0,
    bottomLeftRadius: 0,
  },
  {
    type: "RECTANGLE",
    x: 0,
    y: 513,
    width: 235,
    height: 88,
    fills: [{ type: "SOLID", color: { r: 0, g: 0, b: 0 }, opacity: 1 }],
    topLeftRadius: 4,
    topRightRadius: 4,
    bottomRightRadius: 4,
    bottomLeftRadius: 4,
  },
  {
    x: 32,
    y: 544,
    width: 171,
    height: 24,
    type: "TEXT",
    characters: "This is a centered div.",
    fills: [{ type: "SOLID", color: { r: 1, g: 1, b: 1 }, opacity: 1 }],
    lineHeight: { unit: "PIXELS", value: 24 },
    fontSize: 16,
    fontFamily: "Work Sans, sans-serif",
  },
];
